services:
  mc-server:
    image: itzg/minecraft-server:java21
    container_name: minecraft-cwog-scp
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "NEOFORGE"
      VERSION: "1.21.1"
      MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      GUI: "false"
      TZ: "Europe/Moscow"
      JVM_OPTS: "-javaagent:/data/authlib-injector-1.2.7.jar=https://authserver.ely.by/api/authlib-injector"
    volumes:
      - ./data:/data
    restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       memory: 10G